GET http://localhost:5000/attendances/?month=2020-08
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjFlNDkxZjk3YTBhYTY3MzhkYjQwY2UiLCJlbWFpbCI6ImFkbWluQG1haWwuY29tIiwicHJpdmlsZWdlIjoiYWRtaW4iLCJpYXQiOjE2MDAyNjY1NDl9.cbc-EVkVmSEI9HoGDCSesP-N8DxAREBmYu-Vo_RVogM

###
POST http://localhost:5000/recruitments/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjFhMzY3ZDg4NWU4ZDBmZjBlMjZiMDciLCJlbWFpbCI6ImFkbWluMUBtYWlsLmNvbSIsInByaXZpbGVnZSI6ImFkbWluIiwiaWF0IjoxNTk2NTE5ODIzLCJleHAiOjE1OTY1MjIyMjN9.cX_2oY-CxQ68aFT72b5pbJOX6rXCENA504pAPkEPDnA
Content-Type: application/json

{
  "user": "5f1a3686885e8d0ff0e26b08",
  "date": "2020-07-04",
  "status": "present"
}


###
GET http://localhost:5000/departments?isActive=false
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjJhOTc3NTAzMmViNzUzNjQ2ZDhlNjkiLCJlbWFpbCI6ImtoYWlyQG1haWwuY29tIiwicHJpdmlsZWdlIjoiY2FuZGlkYXRlIiwiaWF0IjoxNTk2NjMwOTAyLCJleHAiOjE1OTY2MzMzMDJ9.ocPXl7KgsH06rBypJIEAcrjJ3CXv6LQ7zy37DCUv3WI



###
POST https://amk.widian-store.com/auth
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "password123"
}

###
PATCH http://localhost:3000/departments/5f18875b18a69f52301e65b3
Content-Type: application/json

{
  "name": "Accounting 1"
}

###
DELETE http://localhost:3000/departments/5f18875b18a69f52301e65b3

###
POST http://localhost:5000/profiles
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyQG1haWwuY29tIiwicHJpdmlsZWdlIjoidXNlciIsImlhdCI6MTU5NTU1NjQ2OSwiZXhwIjoxNTk1NTU4ODY5fQ.qCwDnon_SjNVSblstc5yOOHNbOeK3wd-7pbn-bio1Qs
Content-Type: application/json

{
  "bio": "Hello everybody, my name is user 2 ...",
  "gender": "male",
  "birthPlace": "Batola",
  "birthDate": "1997-02-21"
}

###
PATCH http://localhost:5000/users/5f1e491f97a0aa6738db40ce
Content-Type: application/json

{
  "privilege": "admin"
}


###
DELETE http://localhost:5000/users/reset

