GET http://localhost:5000/users/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjFhMzY4Njg4NWU4ZDBmZjBlMjZiMDgiLCJlbWFpbCI6InVzZXIyQG1haWwuY29tIiwicHJpdmlsZWdlIjoidXNlciIsImlhdCI6MTU5NTc0MDQyNSwiZXhwIjoxNTk1NzQyODI1fQ.k5F84HxLtnDLF9SP_T7-a8A3RcrxdzL5f3ouLBTed7o

###
GET http://localhost:5000/employees/5f1a367d885e8d0ff0e26b07
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjFhMzY3ZDg4NWU4ZDBmZjBlMjZiMDciLCJlbWFpbCI6InVzZXIxQG1haWwuY29tIiwicHJpdmlsZWdlIjoiYWRtaW4iLCJpYXQiOjE1OTU2MTA2OTEsImV4cCI6MTU5NTYxMzA5MX0.5OyKF5TdiHu4gwWh-LeeRaaWGIJA5ufZ2yLN9m6X9RE

###
GET http://localhost:5000/employees
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjFhMzY3ZDg4NWU4ZDBmZjBlMjZiMDciLCJlbWFpbCI6InVzZXIxQG1haWwuY29tIiwicHJpdmlsZWdlIjoiYWRtaW4iLCJpYXQiOjE1OTU2MTA2OTEsImV4cCI6MTU5NTYxMzA5MX0.5OyKF5TdiHu4gwWh-LeeRaaWGIJA5ufZ2yLN9m6X9RE



###
POST http://localhost:5000/auth
Content-Type: application/json

{
  "email": "user2@mail.com",
  "password": "password123"
}

###
PATCH http://localhost:3000/departments/5f18875b18a69f52301e65b3
Content-Type: application/json

{
  "name": "Accounting 1"
}

###
DELETE http://localhost:3000/departments/5f18875b18a69f52301e65b3

###
POST http://localhost:5000/profiles
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyQG1haWwuY29tIiwicHJpdmlsZWdlIjoidXNlciIsImlhdCI6MTU5NTU1NjQ2OSwiZXhwIjoxNTk1NTU4ODY5fQ.qCwDnon_SjNVSblstc5yOOHNbOeK3wd-7pbn-bio1Qs
Content-Type: application/json

{
  "bio": "Hello everybody, my name is user 2 ...",
  "gender": "male",
  "birthPlace": "Batola",
  "birthDate": "1997-02-21"
}

###
PATCH http://localhost:5000/users/5f1a367d885e8d0ff0e26b07
Content-Type: application/json

{
  "privilege": "admin"
}


###
DELETE http://localhost:5000/users/reset

