GET http://localhost:5000/employees/5f2ab3a8ea335f35f007bae7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjFhMzY3ZDg4NWU4ZDBmZjBlMjZiMDciLCJlbWFpbCI6ImFkbWluMUBtYWlsLmNvbSIsInByaXZpbGVnZSI6ImFkbWluIiwiaWF0IjoxNTk3NzMzNTQ3LCJleHAiOjE1OTc3MzU5NDd9.ABUrdUyO-hGojyIpKIVa6SklfLFRK5Vt-S6A4RwUAPM

###
POST http://localhost:5000/recruitments/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjFhMzY3ZDg4NWU4ZDBmZjBlMjZiMDciLCJlbWFpbCI6ImFkbWluMUBtYWlsLmNvbSIsInByaXZpbGVnZSI6ImFkbWluIiwiaWF0IjoxNTk2NTE5ODIzLCJleHAiOjE1OTY1MjIyMjN9.cX_2oY-CxQ68aFT72b5pbJOX6rXCENA504pAPkEPDnA
Content-Type: application/json

{
  "user": "5f1a3686885e8d0ff0e26b08",
  "date": "2020-07-04",
  "status": "present"
}


###
GET http://localhost:5000/assessments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjJhOTc3NTAzMmViNzUzNjQ2ZDhlNjkiLCJlbWFpbCI6ImtoYWlyQG1haWwuY29tIiwicHJpdmlsZWdlIjoiY2FuZGlkYXRlIiwiaWF0IjoxNTk2NjMwOTAyLCJleHAiOjE1OTY2MzMzMDJ9.ocPXl7KgsH06rBypJIEAcrjJ3CXv6LQ7zy37DCUv3WI



###
POST http://localhost:5000/auth
Content-Type: application/json

{
  "email": "admin1@mail.com",
  "password": "password123"
}

###
PATCH http://localhost:3000/departments/5f18875b18a69f52301e65b3
Content-Type: application/json

{
  "name": "Accounting 1"
}

###
DELETE http://localhost:3000/departments/5f18875b18a69f52301e65b3

###
POST http://localhost:5000/profiles
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyQG1haWwuY29tIiwicHJpdmlsZWdlIjoidXNlciIsImlhdCI6MTU5NTU1NjQ2OSwiZXhwIjoxNTk1NTU4ODY5fQ.qCwDnon_SjNVSblstc5yOOHNbOeK3wd-7pbn-bio1Qs
Content-Type: application/json

{
  "bio": "Hello everybody, my name is user 2 ...",
  "gender": "male",
  "birthPlace": "Batola",
  "birthDate": "1997-02-21"
}

###
PATCH http://localhost:5000/users/5f1e491f97a0aa6738db40ce
Content-Type: application/json

{
  "privilege": "admin"
}


###
DELETE http://localhost:5000/users/reset

